### PR TITLE
Add gcp_token in AccessCredentialType for google cloud service accounts

### PR DESCRIPTION
**Pull request by SarantopoulosKon**

### CODE REVIEW

**Comment by thetorpedodog** [comment]
Can we just use "token"? The mix of the generic "key" and the provider-specific "azure key" "gcp key" "arn" is not ideal.

**Comment by SarantopoulosKon** [comment]
> Can we just use "token"? The mix of the generic "key" and the provider-specific "azure key" "gcp key" "arn" is not ideal.

That makes sense, what worries me though is that we will break any code using this model.

**Comment by thetorpedodog** [comment]
> > Can we just use "token"? The mix of the generic "key" and the provider-specific "azure key" "gcp key" "arn" is not ideal.
> 
> That makes sense, what worries me though is that we will break any code using this model.

What if we treat "azure_token" as an alias for "token" in inputs? That doesn't break any code that uses it but means we don't have to introduce any more.

**Comment by SarantopoulosKon** [comment]
> > > Can we just use "token"? The mix of the generic "key" and the provider-specific "azure key" "gcp key" "arn" is not ideal.
> > 
> > 
> > That makes sense, what worries me though is that we will break any code using this model.
> 
> What if we treat "azure_token" as an alias for "token" in inputs? That doesn't break any code that uses it but means we don't have to introduce any more.

Let me know if my change makes any sense.

**Comment by antalakas** [comment]
[sc-44977] [skip-ch]

**Review by thetorpedodog — APPROVED** [review]
Great! Sorry for not getting back to this earlier.

**Pull request merged**
